### ISSUE TITLE
Need to change from docker-compose to docker compose

### ISSUE THREAD

**Issue by WisarutBholsithi** [nezhar/jupyter-docker-compose#4]
Hi everybody,
I have download to jupyter-docker-compose to use in my docker with container based on ubuntu18.04 and python3.10.
However, I have learnt that docker-compose no longer being updated, so it has give me the following error while using command **docker-compose build**

> oot@31ad2d8c4434:/wizdir/jupyter-docker-compose# docker-compose build
> Traceback (most recent call last):
>   File "/usr/local/bin/docker-compose", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/site-packages/compose/cli/main.py", line 81, in main
>     command_func()
>   File "/usr/local/lib/python3.10/site-packages/compose/cli/main.py", line 200, in perform_command
>     project = project_from_options('.', options)
>   File "/usr/local/lib/python3.10/site-packages/compose/cli/command.py", line 60, in project_from_options
>     return get_project(
>   File "/usr/local/lib/python3.10/site-packages/compose/cli/command.py", line 152, in get_project
>     client = get_client(
>   File "/usr/local/lib/python3.10/site-packages/compose/cli/docker_client.py", line 41, in get_client
>     client = docker_client(
>   File "/usr/local/lib/python3.10/site-packages/compose/cli/docker_client.py", line 124, in docker_client
>     kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
> TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

After I have read the advice to use "docker compose build" instead of "docker-compose build" as suggested by [Migrate to Compose V2](https://docs.docker.com/compose/releases/migrate/), I got the following error:

> root@31ad2d8c4434:/wizdir/jupyter-docker-compose# docker compose build
> [+] Building 0.0s (0/0)
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

What to be done with this kind of problem?

BTW, the requirement packages in my system are:
python3.10 -m pip index versions numpy => 1.26.4
python3.10 -m pip index versions pandas => 2.2.3
python3.10 -m pip index versions matplotlib => 3.9.2

**Comment by nezhar** [comment]
It should work with both, I updated however the readme.

Are there any additional changes in your Dockefile?
