### ISSUE TITLE
Images hosted on Docker Hub are no longer updated. Please use quay.io image⁠ 

### ISSUE THREAD

**Issue by marsteel** [nezhar/jupyter-docker-compose#6]
https://hub.docker.com/r/jupyter/minimal-notebook

Images hosted on Docker Hub are no longer updated. Please, use [quay.io image⁠](https://quay.io/repository/jupyter/minimal-notebook)

```
#FROM jupyter/minimal-notebook
FROM quay.io/jupyter/minimal-notebook:latest
```

**Comment by nezhar** [comment]
Thanks, good to now, I also found that in the readme now:

> Since 2023-10-20 our images are only pushed to Quay.io registry. Older images are available on Docker Hub, but they will no longer be updated.

I will create a PR for this
